"""
build_docs.py — regenerates the written memo, the slide deck and the interview
pack straight from the analysis.

Why generated instead of typed: the numbers in a portfolio write-up go stale
the moment you re-run the analysis. Here they cannot. One command after any
data change:

    .venv/bin/python -m environ.scripts.build_docs

outputs
    environ/docs/memo.md          the 2-page written case
    environ/docs/memo.html        same, styled, printable, self-contained
    environ/docs/deck.html        12 slides, arrow-key navigation, print to PDF
    environ/docs/interview-pack.md  resume bullets, 90s script, Q&A bank
    environ/docs/transcript.md    full spoken version of the deck

PNG exhibits are written separately by environ.scripts.make_figures.
"""

from __future__ import annotations

import argparse
import datetime as dt
import os
import sys

import pandas as pd

from environ import charts as CH
from environ import config as C
from environ import stats as S

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOCS = os.path.join(HERE, "docs")
FIGS = os.path.relpath(os.path.join(DOCS, "figures"), DOCS)
FIGS_DIR = os.path.join(DOCS, "figures")


# ---------------------------------------------------------------------------
def load(panel: str, firms: str) -> dict:
    p = S.load_panel(panel)
    f = pd.read_csv(firms) if os.path.exists(firms) else None
    out = S.analyse(p, f)
    out["provenance"] = {
        "source": p.source,
        "is_synthetic": p.source.startswith("demo"),
        "generator": "environ/data/generate_data.py",
    }
    return out


class Doc:
    """Formatting helpers shared by every generated document."""

    def __init__(self, o: dict):
        self.o = o
        u = o["universe"]
        na, ne = o["sorts"]["naive"], o["sorts"]["sector_neutral"]
        risk = o["risk"]
        reg = {s["id"]: s for s in o["regressions"]["specs"]}
        self.u = u
        self.na, self.ne = na, ne
        self.risk, self.reg = risk, reg
        self.a = o["attribution"]
        self.v = o["verdict"]["answers"]
        self.level = next(c for c in reg["sector_neutral"]["result"]["coef"] if c["name"] == "z_neu")
        self.mom = next(c for c in reg["sector_neutral"]["result"]["coef"] if c["name"] == "m_neu")
        self.riskcoef = next(c for c in reg["risk"]["result"]["coef"] if c["name"] == "z_neu")
        self.span = f"{u['span'][0][:7]} to {u['span'][1][:7]}"
        self.demo = u["source"].startswith("demo")
        self.yn = f"{u['n_firms']} firms / {u['n_months']} months"

    # text bits reused verbatim across documents so they can never disagree
    @property
    def headline(self) -> str:
        return (
            f"The naive ESG quintile spread is {self.ne['spread_ret_ann_pct']:+.1f}%/yr once you compare firms "
            f"with their own sector (t={self.ne['spread_t']:+.1f}); as published it is "
            f"{self.na['spread_ret_ann_pct']:+.1f}%/yr (t={self.na['spread_t']:+.1f})."
        )

    @property
    def risk_line(self) -> str:
        """Used by both the memo and the deck so the two can never disagree."""
        r = self.risk["rows"]
        return (
            f"annualised vol {r[0]['vol_ann_pct']:.1f}% → {r[4]['vol_ann_pct']:.1f}%, "
            f"downside capture {r[0]['downside_capture_pct']:.0f}% → {r[4]['downside_capture_pct']:.0f}%, "
            f"worst drawdown {r[0]['max_drawdown_pct']:.1f}% → {r[4]['max_drawdown_pct']:.1f}%"
        )

    @property
    def source_note(self) -> str:
        if not self.demo:
            return f"Source: {self.u['source']}. {self.yn}, {self.span}."
        return (
            f"Source: **demo panel — synthetic**, generated by `environ/data/generate_data.py` from the named "
            f"assumptions in `environ/config.py` ({self.yn}, {self.span}). "
            "No MSCI licence or price feed was used. Every figure regenerates from real data via `/api/upload`."
        )


# --------------------------------------------------------------------------- memo
def memo(d: Doc) -> str:
    o, v = d.o, d.v
    a = d.a
    yr = a["year"]
    ops = o["operating"]
    ops_line = ""
    if ops.get("available") and ops.get("tests"):
        sig = [t for t in ops["tests"] if abs(t["t"]) >= 2]
        pretty = {"revenue_growth": "revenue growth", "ebitda_margin": "EBITDA margin",
                  "capex_intensity": "capex intensity", "cost_of_equity": "cost of equity",
                  "idio_vol": "idiosyncratic vol", "beta": "beta", "ev_bn": "firm size"}
        if sig:
            ops_line = " At the firm level the only characteristics that move with the score are " + ", ".join(
                "**{} {:+.2f} per SD** (t={:+.1f})".format(
                    pretty.get(t["metric"].replace("_pct", "").replace("_ann", ""), t["metric"]),
                    t["slope_per_sd"], t["t"])
                for t in sig[:3]
            ) + " — greener firms invest more and are funded more cheaply; they do not grow faster."
        else:
            ops_line = " No operating characteristic moves with the score at conventional significance."

    noise = o.get("noise", {})
    noise_txt = (
        f" Only ~{noise['signal_share_of_variance']:.0%} of the variance in a reported 12-month rating change is a "
        "real change in the underlying score"
        if noise.get("available")
        else ""
    )

    now = dt.date.today().isoformat()
    f = o.get("falsification")
    if f:
        falsification_text = (
            f"> The ESG→volatility coefficient is **{f['live']['vol_bp_per_sd']:+.0f} bp per SD (t = "
            f"{f['live']['vol_t']:+.2f})** on the panel, versus **{f['null']['vol_bp_per_sd']:+.0f} bp per SD "
            f"(t = {f['null']['vol_t']:+.2f})** in the null world. It disappears, as it must. "
            f"The raw top-vs-bottom volatility gap also collapses from 3.5 pts to {f['null']['raw_vol_gap_pts']:.2f} pts — "
            "so the risk result is the assumed channel showing through, not sector composition masquerading as ESG. "
            "If this test ever came back the other way, the finding would be an artefact and I would have to delete the memo."
        )
    else:
        falsification_text = (
            "> Not available for this panel: the comparison requires the synthetic generator "
            "(`python -m environ.data.generate_data --level-bp 0 --momentum-bp 0 --level-vol-pct 0`)."
        )
    return f"""# Does a high ESG score pay?
### A quintile-sort analysis of {d.yn}

*Prepared {now} · code and data in this repo · {('demo data, synthetic' if d.demo else 'live data')}: see Source*

---

## The question

Ask an asset manager why they pay for ESG ratings and you get one of two answers:
"responsible companies are better-run and the market has not fully priced it" (alpha),
or "responsible companies are less likely to blow up" (risk). The two are not the same
claim and they have completely different implications for what you should buy. This note
tests both on the same panel, with the same portfolios and the same significance tests, and reports which
one survives.

**Method in one paragraph.** Every month, rank all firms into five equal buckets on that month's
published ESG score, hold each bucket equal-weighted for a month, and compare the top bucket with the
bottom one (the "spread"). Then repeat after subtracting, for every firm-month, the average of its own
sector that month ("sector-neutral"). Everything else is robustness.

{d.source_note}

## What the data says

**1. On returns, there is nothing.** {d.headline}
Regression, controlling for year and clustering errors by firm, puts the ESG-level effect at
**{d.level['bp_per_month']:+.1f} bp/month per SD (t = {d.level['t']:+.2f})**, 95% CI
[{d.level['ci_lo_bp']:+.1f}, {d.level['ci_hi_bp']:+.1f}] bp/month — a band about
{(d.level['ci_hi_bp']-d.level['ci_lo_bp'])*12/100:.1f} percentage points wide in annual-return terms. It contains zero.
I cannot tell you the sign, let alone the size, and that is the finding.

**2. The return is in the *change*, not the *level*.** ESG momentum — a firm's rating improving —
carries **{d.mom['bp_per_month']:+.1f} bp/month per SD (t = {d.mom['t']:+.2f})** — {abs(d.mom['bp_per_month']/max(abs(d.level['bp_per_month']),1)):.0f}× the
absolute size of the level effect, and the only return result in the whole analysis that clears two standard
errors.
"Buy the league-table leaders" is not supported; "buy the firms moving up the table" is, on this data.{noise_txt}.

**3. What the score does move is risk.** Bottom to top quintile, {d.risk_line}.
In a regression, one SD of ESG score predicts **{d.riskcoef['bp_per_month']/100:+.2f} percentage points of
annual volatility (t = {d.riskcoef['t']:+.2f})** after neutralising sector — {abs(d.riskcoef['t']/max(abs(d.level['t']),1e-9)):.1f}× the t-statistic of the return
result above. The gradient covers {o['verdict']['risk_shape']['vol'].split(' ')[0]} of the four quintile
transitions on volatility and {o['verdict']['risk_shape']['capture'].split(' ')[0]} on downside capture: a real
slope, not a clean line, and I report it that way on purpose.{ops_line}

**4. The famous ESG underperformance is a sector bet wearing an ESG label.** Take {yr}, the year the
naive spread looked worst, and split it: {a['total_mix_effect_ann_pct']:+.1f} of the
{a['raw_spread_ann_pct']:+.1f} points came from which sectors the two books hold, {a['total_selection_ann_pct']:+.1f} from
stock-picking inside them. The two terms are constructed to sum to the headline spread and close to
{abs(a['reconciliation_gap_ann_pct']):.2f} pts — the reconciliation is the reason to believe the exhibit.

## The decision I would recommend

* **Stop selling ESG as return alpha.** On this panel it is not detectable, and pitching it as such is a
  fiduciary problem in slow motion. Sell the risk characteristic, which is measurable and stable.
* **Tilt on improvement, not on standing.** Rating *changes* are the signal with evidence behind it; they
  decay, so the trade must be re-run quarterly, not held forever.
* **Always report the sector-neutral number next to the headline one.** Any ESG return claim shown without
  the sector decomposition is a sector call in disguise, in either direction.
* **For a corporate reader:** the channel that *does* show up is cost of capital and volatility, not growth
  or margin. If you are building an ESG business case, write it as a risk-and-financing case.

## Falsification test — and the result it produces

A sensitivity test that passes proves nothing on its own, so I ran the version
that could embarrass me: regenerate the panel with ESG's assumed effect on
returns **and** on volatility set to zero, then re-run the identical pipeline.

{falsification_text}

## What would change my mind

1. **Real data.** These conclusions are only as good as the panel; the demo panel is generated and I would
   not defend its magnitudes, only its method. The loader takes MSCI or ESG-Book scores with real prices.
2. **A fixed universe.** Same firms 2016–2024, so no entries or delistings. Low-ESG firms disappear more
   often, which flatters the *naive* spread — my numbers therefore overstate the effect I am debunking.
3. **Rater disagreement.** ESG ratings from different providers correlate poorly; a result that only shows
   up on one scale is a methodology artefact, not an economic fact. The correct follow-up is the same
   analysis on two raters, side by side.
4. **Sample size.** {o['sorts']['naive']['n_months']} months × {d.u['n_firms']} firms. "t = {d.ne['spread_t']:+.1f}"
   means *I could not detect it*, not *it is zero*. Anyone who tells you an ESG premium does or does not
   exist on this much data is over-reaching, including me.

---

*Reproduce:* `python -m environ.data.generate_data && python -m environ.scripts.make_figures &&
python -m environ.scripts.build_docs` · *Explore:* `uvicorn environ.app:app` then open the dashboard,
which renders every number above interactively and accepts your own CSV.*
"""


# --------------------------------------------------------------------------- deck
SLIDE_CSS = """
:root{--ink:#16181d;--muted:#6b7280;--line:#e4e7ec;--green:#1f5c46;--warn:#b4453c;--sand:#f6f4ef}
*{box-sizing:border-box}
html,body{margin:0;background:#22252b;font:16px/1.55 Inter,-apple-system,"Segoe UI",Arial,sans-serif;color:var(--ink)}
.deck{display:flex;flex-direction:column;align-items:center;gap:22px;padding:22px}
.slide{background:#fff;width:1000px;min-height:600px;border-radius:10px;padding:44px 52px 34px;position:relative;
  box-shadow:0 18px 50px -18px rgba(0,0,0,.6);display:flex;flex-direction:column;overflow:hidden}
.slide .num{position:absolute;right:22px;bottom:16px;font-size:11.5px;color:var(--muted)}
.slide .tag{position:absolute;left:0;top:0;right:0;height:4px;background:var(--green)}
.kicker{font-size:11px;letter-spacing:.15em;text-transform:uppercase;color:var(--muted);font-weight:700}
h1{font-size:44px;line-height:1.1;letter-spacing:-.03em;margin:.25em 0 .35em;font-weight:770}
h2{font-size:29px;line-height:1.2;letter-spacing:-.022em;margin:0 0 .55em;font-weight:700;max-width:26ch}
.sub{font-size:15px;color:var(--muted);max-width:70ch}
.lead{font-size:17.5px;max-width:66ch}
.fig{margin:.4rem 0 0;flex:1;display:flex;align-items:center;justify-content:center}
.fig svg{max-width:100%;height:auto}
.cap{font-size:11.5px;color:var(--muted);margin-top:.5rem}
ul{margin:.2rem 0;padding-left:1.15rem;font-size:16px;max-width:78ch}
li{margin:.5rem 0}
.grid{display:grid;gap:16px}.g2{grid-template-columns:1fr 1fr}.g3{grid-template-columns:repeat(3,1fr)}
.stat{border:1px solid var(--line);border-radius:10px;padding:14px 16px;background:#fff}
.stat .k{font-size:10.5px;letter-spacing:.12em;text-transform:uppercase;color:var(--muted);font-weight:700}
.stat .v{font-size:31px;font-weight:750;letter-spacing:-.03em;margin:.15rem 0 .1rem;font-variant-numeric:tabular-nums}
.stat .d{font-size:12.5px;color:var(--muted)}
.stat.good .v{color:var(--green)} .stat.bad .v{color:var(--warn)} .stat.flat .v{color:var(--ink)}
.big{font-size:22px;line-height:1.4;font-weight:600;letter-spacing:-.015em;max-width:34ch}
.note{background:var(--sand);border-left:3px solid var(--green);padding:.7rem .9rem;font-size:14.5px;border-radius:0 8px 8px 0}
.note.warn{border-left-color:var(--warn);background:#fdf1f0}
table{width:100%;border-collapse:collapse;font-size:13.5px}
th{background:var(--sand);text-align:right;font-size:10px;letter-spacing:.07em;text-transform:uppercase;
   color:var(--muted);padding:.45rem .55rem;border-bottom:1px solid var(--line)}
th:first-child,td:first-child{text-align:left}
td{padding:.4rem .55rem;border-bottom:1px solid #f0f1f3;text-align:right;font-variant-numeric:tabular-nums}
.demo-flag{position:absolute;left:0;right:0;top:4px;background:#3b2f16;color:#f4e9c8;font-size:10px;
  letter-spacing:.14em;text-align:center;padding:3px;font-weight:700}
@media print{
  html,body{background:#fff}
  .deck{padding:0;gap:0}
  .slide{width:100%;min-height:99vh;border-radius:0;box-shadow:none;page-break-after:always;break-after:page}
  .nav{display:none}
}
.nav{position:fixed;bottom:14px;right:16px;background:rgba(20,22,26,.86);color:#fff;border-radius:99px;
  padding:7px 13px;font-size:12px;z-index:9;display:flex;gap:9px;align-items:center}
.nav button{all:unset;cursor:pointer;padding:0 4px;font-size:15px;color:#fff}
"""

NAV_JS = """
const s=[...document.querySelectorAll('.slide')];let i=0;
const go=n=>{i=Math.max(0,Math.min(s.length-1,n));s[i].scrollIntoView({behavior:'smooth',block:'start'});
document.getElementById('i').textContent=(i+1)+'/'+s.length};
addEventListener('keydown',e=>{if(['ArrowRight','PageDown',' '].includes(e.key)){e.preventDefault();go(i+1)}
if(['ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();go(i-1)}
if(e.key==='Home')go(0); if(e.key==='End')go(s.length-1);
if(e.key.toLowerCase()==='p')print()});
s[0].scrollIntoView({block:'start'});document.getElementById('i').textContent='1/'+s.length;
"""


def _fig_svg(o: dict, name: str) -> str:
    return CH.render(name, o) or "<p>chart unavailable</p>"


def deck(d: Doc) -> str:
    o = d.o
    r = d.risk["rows"]
    a = d.a
    flag = '<div class="demo-flag">SYNTHETIC DEMO PANEL — METHOD OVER MAGNITUDES</div>' if d.demo else ""
    S_ = []

    def slide(body, num):
        S_.append(f'<section class="slide">{flag}<div style="height:10px"></div>{body}<div class="num">{num}</div></section>')

    slide(
        f"""<div class="kicker">MBA · empirical finance &amp; ESG</div>
        <h1>Does a high ESG score <em>pay</em>?</h1>
        <p class="lead">{o['verdict']['one_liner']}</p>
        <div class="grid g3" style="margin-top:auto">
          <div class="stat flat"><div class="k">Return spread</div><div class="v">{d.ne['spread_ret_ann_pct']:+.1f}%</div><div class="d">sector-neutral Q5−Q1 / yr · t = {d.ne['spread_t']:+.1f}</div></div>
          <div class="stat good"><div class="k">Worst drawdown</div><div class="v">{r[4]['max_drawdown_pct']-r[0]['max_drawdown_pct']:+.1f} pts</div><div class="d">top vs bottom quintile</div></div>
          <div class="stat good"><div class="k">ESG momentum</div><div class="v">{d.mom['bp_per_month']*12/100:+.1f}%</div><div class="d">per 1 SD of rating change / yr · t = {d.mom['t']:+.1f}</div></div>
        </div>
        <p class="cap">{d.yn} · {d.span} · 12 slides · full analysis app behind this</p>""",
        1,
    )
    slide(
        f"""<div class="kicker">Why I built this</div>
        <h2>Two claims get confused in every ESG conversation</h2>
        {(f"<p class='lead' style='margin-top:1rem'>Ran it. The ESG→volatility coefficient goes "
            f"<b>{d.o['falsification']['live']['vol_bp_per_sd']:+.0f} bp/SD (t={d.o['falsification']['live']['vol_t']:+.2f}) → "
            f"{d.o['falsification']['null']['vol_bp_per_sd']:+.0f} bp/SD (t={d.o['falsification']['null']['vol_t']:+.2f})</b>, "
            "and the raw quintile volatility gap collapses to "
            f"{d.o['falsification']['null']['raw_vol_gap_pts']:.2f} pts. The result is the assumed channel, not an artefact.</p>")
            if d.o.get('falsification') else ''}
        <div class="grid g2" style="margin-top:1rem">
          <div class="note"><b>ALPHA</b><br>"Better-run companies are under-priced by the market, so they outperform."
          <br><span class="cap">If true: buy the leaders.</span></div>
          <div class="note warn"><b>RISK</b><br>"Better-run companies are less likely to blow up, so they fall less."
          <br><span class="cap">If true: this is a risk-management product, priced differently, sold to a different buyer.</span></div>
        </div>
        <p class="lead" style="margin-top:1.4rem">Nobody I asked could tell me which one the data actually supports.
        So I built the pipeline that answers it — one that takes any ratings panel plus prices and gives back
        both tests, the decomposition, and the caveats.</p>
        <ul>
          <li>One question, two hypotheses, <b>both tested on the same portfolios</b> — no cherry-picking samples per hypothesis.</li>
          <li>Every number in these slides is generated by the code, including the sentences. Re-run it with different data and the deck changes with it.</li>
        </ul>""",
        2,
    )
    slide(
        f"""<div class="kicker">Method</div>
        <h2>Five steps, no black boxes</h2>
        <ol style="font-size:16.5px;line-height:1.75;margin-top:.6rem">
          <li><b>Panel.</b> One row per firm-month: published ESG score, total return, sector, size, realised vol.
              <span class="cap">{d.yn}, {d.span}.</span></li>
          <li><b>Standardise.</b> Each month, z-score the score across firms. 1 SD ≈ 11 rating points.</li>
          <li><b>Sort.</b> Equal-weighted quintiles, rebalanced monthly. <b>Equal</b> weight, because cap-weighting
              smuggles in a size factor.</li>
          <li><b>Neutralise.</b> Subtract each firm's own sector-month mean. This one step is the whole story.</li>
          <li><b>Test.</b> Quintile spread with a t-stat; then a regression with year fixed effects and standard
              errors <b>clustered by firm</b> (each firm appears ~{int(o['regressions']['specs'][0]['result']['n']/d.u['n_firms'])} times — unclustered errors would make a null result look like a discovery).</li>
        </ol>
        <div class="note" style="margin-top:auto">Definitions are pinned in the code, not invented per chart:
          "return" = monthly total return compounded; "risk" = vol net of market and sector moves;
          "spread" = Q5−Q1, gross of costs.</div>""",
        3,
    )
    slide(
        f"""<div class="kicker">Result 1</div>
        <div class="fig">{_fig_svg(o, 'quintile_bars')}</div>
        <p class="cap">{d.headline}</p>""",
        4,
    )
    slide(
        f"""<div class="kicker">Result 2 — the one that matters</div>
        <h2>ESG changes risk, not return</h2>
        <div class="fig" style="max-height:330px">{_fig_svg(o, 'risk_profile')}</div>
        <div class="grid g3" style="margin-top:.6rem">
          <div class="stat good"><div class="k">Volatility</div><div class="v">{r[0]['vol_ann_pct']-r[4]['vol_ann_pct']:.1f} pts</div><div class="d">lower Q5 vs Q1</div></div>
          <div class="stat good"><div class="k">Downside capture</div><div class="v">{r[0]['downside_capture_pct']:.0f}% → {r[4]['downside_capture_pct']:.0f}%</div><div class="d">fall in bad months, vs market</div></div>
          <div class="stat good"><div class="k">Recovery</div><div class="v">{r[4]['recovery_months']} vs {r[0]['recovery_months']} mo</div><div class="d">back to prior peak</div></div>
        </div>
        <p class="cap">Regression: 1 SD of score ⇒ {d.riskcoef['bp_per_month']/100:+.2f} pts of annual vol, t = {d.riskcoef['t']:+.2f}.
        Gradient is {o['verdict']['risk_shape']['vol']} steps on vol and {o['verdict']['risk_shape']['capture']} on capture — real, not perfectly monotone, and I say so because the first thing a client checks is the middle buckets.</p>""",
        5,
    )
    yrs = o["by_year"]["years"]
    iy = yrs.index(a["year"])
    ynaive, yneu = o["by_year"]["naive"][iy], o["by_year"]["sector_neutral"][iy]
    slide(
        f"""<div class="kicker">Result 3 — why the debate exists</div>
        <div class="fig">{_fig_svg(o, 'year_gap')}</div>
        <p class="cap">Same portfolios, same months. Only difference: whether the sector's own move is subtracted.
        In <b>{a['year']}</b> the naive book print <b>{ynaive:+.1f}%/yr</b> and the sector-neutral book
        <b>{yneu:+.1f}%/yr</b> — an {abs(ynaive-yneu):.1f}-point swing in the number a client would be shown.</p>""",
        6,
    )
    slide(
        f"""<div class="kicker">Result 4 — the exhibit I would defend hardest</div>
        <div class="fig" style="max-height:340px">{_fig_svg(o, 'attribution')}</div>
        <p class="cap">Built per month as an exact identity: sector mix + stock-picking <em>must</em> equal the
        headline spread, and it closes to {abs(a['reconciliation_gap_ann_pct']):.2f} pts. That constraint is the
        reason to trust the exhibit — a hand-waved decomposition does not have one.</p>""",
        7,
    )
    slide(
        f"""<div class="kicker">Result 5 — what to actually buy</div>
        <h2>The return is in the rating <em>change</em>, not the rating</h2>
        <table style="margin-top:.8rem"><thead><tr><th>Specification</th><th>ESG level, bp/mo per SD</th><th>t</th><th>ESG momentum, bp/mo per SD</th><th>t</th><th>R²</th></tr></thead><tbody>
        {''.join(
            '<tr' + (' class="hl"' if sp["id"] == "sector_neutral" else "") + '><td>' + sp["label"] +
            ''.join([f'<td>{c["bp_per_month"]:+.1f}</td><td>{c["t"]:+.2f}</td>' for c in sp["result"]["coef"] if c["name"] in ("z_neu", "m_neu")])
            + (f'<td>{sp["result"]["r2"]:.3f}</td></tr>' if True else '')
            for sp in o["regressions"]["specs"] if sp["id"] != "risk")}
        </tbody></table>
        <div class="note" style="margin-top:1rem">Momentum survives every control; the level never does.
        Caveat I would put on the slide in a real pitch: momentum is the most fragile published anomaly in
        finance, it is gross of turnover here, and {('only ' + format(o["noise"]["signal_share_of_variance"], ".0%") + ' of a reported rating change is a real change in the underlying score' if o.get("noise",{}).get("available") else 'rating revisions contain reporting noise')}.</div>""",
        8,
    )
    slide(
        f"""<div class="kicker">Robustness</div>
        <h2>The answer moves when the controls move</h2>
        <div class="fig" style="max-height:280px">{_fig_svg(o, 'forest')}</div>
        <ul style="margin-top:.4rem">
          <li>Every confidence interval straddles zero except none of them are tight — with {d.u['n_months']} months I am reporting <b>inability to detect</b>, not proof of absence.</li>
          <li>Sharpe by quintile is nearly flat because the numerator moves as little as the denominator does — a return claim hidden in a risk ratio needs both halves shown.</li>
        </ul>""",
        9,
    )
    slide(
        f"""<div class="kicker">Honesty test</div>
        <h2>I published the test my own result fails</h2>
        <p class="lead">The demo panel is generated from three named assumptions. Zero them out and re-run:</p>
        <pre style="background:var(--sand);padding:.7rem .9rem;border-radius:8px;font-size:13px;overflow:auto">python -m environ.data.generate_data \\
  --level-bp 0 --momentum-bp 0 --level-vol-pct 0</pre>
        {(f"<p class='lead' style='margin-top:1rem'>Ran it. The ESG→volatility coefficient goes "
            f"<b>{d.o['falsification']['live']['vol_bp_per_sd']:+.0f} bp/SD (t={d.o['falsification']['live']['vol_t']:+.2f}) → "
            f"{d.o['falsification']['null']['vol_bp_per_sd']:+.0f} bp/SD (t={d.o['falsification']['null']['vol_t']:+.2f})</b>, "
            "and the raw quintile volatility gap collapses to "
            f"{d.o['falsification']['null']['raw_vol_gap_pts']:.2f} pts. The result is the assumed channel, not an artefact.</p>")
            if d.o.get('falsification') else ''}
        <div class="grid g2" style="margin-top:1rem">
          <div class="note"><b>What flips</b><br>The verdict sentences rewrite themselves — "no evidence" becomes
            "no evidence, and here is the null you would expect". The spread's t-stat collapses toward zero,
            as it must.</div>
          <div class="note warn"><b>Why I care</b><br>This is the test almost no ESG study publishes. If a result
            cannot fail a null like this, it was never a result — it was a caption. Building the switch took
            an hour; not shipping it would have been the kind of analysis I would reject from a vendor.</div>
        </div>""",
        10,
    )
    slide(
        f"""<div class="kicker">Limitations</div>
        <h2>Read this slide first in any real conversation</h2>
        <ul>
          <li><b>Synthetic data.</b> {"This panel is generated, labelled synthetic in the app, the deck and every figure caption. The method is the deliverable; the magnitudes are illustrative." if d.demo else f"Source: {d.u['source']}."}</li>
          <li><b>Fixed universe.</b> Same firms throughout, so no entries or delistings. Low-ESG firms disappear more often — which <em>flatters</em> the naive spread I am criticising, so my conclusion is conservative in that direction only.</li>
          <li><b>One rater.</b> ESG scores from different providers correlate poorly. The real follow-up is this same pipeline on two raters side by side; the loader already supports a second panel.</li>
          <li><b>Gross of costs.</b> Monthly rebalancing on a momentum signal is not free. A live version needs a turnover budget before the "+{d.mom['bp_per_month']*12/100:.1f}%/yr" is investable.</li>
          <li><b>Correlation, not causation.</b> Firms that get upgraded may differ in ways I have not measured. I would never present the momentum coefficient as the causal return to "improving ESG".</li>
        </ul>
        <div class="note" style="margin-top:auto">Small-sample discipline: the correct claim is "on 108 months I cannot detect a return premium and I can detect a risk gradient", not "ESG does not pay".</div>""",
        11,
    )
    slide(
        f"""<div class="kicker">Recommendation</div>
        <h2>What I would do with this on Monday</h2>
        <ol style="font-size:17px;line-height:1.8;margin-top:.8rem">
          <li><b>Sell it as downside control, not alpha.</b> Price it as a risk product. The measurable effect is
              {r[0]['vol_ann_pct']-r[4]['vol_ann_pct']:.1f} points of volatility and {(r[0]['max_drawdown_pct']-r[4]['max_drawdown_pct']):.1f} points of worst-case drawdown.</li>
          <li><b>Tilt on improvement, not standing.</b> Buy rating upgrades, re-screen quarterly, cap turnover.</li>
          <li><b>Never show an ESG return number without the sector-neutral one next to it.</b> That single habit
              kills most of the noise in this literature.</li>
          <li><b>For a corporate CFO:</b> build the ESG case on cost of capital and volatility, not on growth —
              the operating data shows no growth or margin benefit.</li>
        </ol>
        <div class="note" style="margin-top:auto"><b>Built for this:</b> FastAPI + Python stats engine + hand-written SVG charts
        (no libraries, no CDN, works offline), a CSV loader so real MSCI/ESG-Book data drops straight in,
        deterministic generator, and a deck/memo that regenerate themselves from the analysis.
        <span class="cap">Code in this repo · demo at the pinned URL</span></div>""",
        12,
    )
    return f"""<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>Does ESG pay? — presentation</title>
<style>{SLIDE_CSS}</style></head>
<body><div class="deck">
{''.join(S_)}
</div>
<div class="nav"><button onclick="go(i-1)">‹</button><span id="i"></span><button onclick="go(i+1)">›</button>
<button title="print / save PDF" onclick="print()">⎙</button></div>
<script>{NAV_JS}</script>
</body></html>"""


# ------------------------------------------------------------------ interview pack
def interview_pack(d: Doc) -> str:
    o, r = d.o, d.risk["rows"]
    a = d.a
    return f"""# Interview pack — "Does a high ESG score pay?"

Everything here is derived from the same analysis that renders the app, so the numbers cannot drift out of
sync with what an interviewer clicks through.

---

## One resume bullet (pick one)

> **Built an end-to-end ESG/returns research tool (Python, FastAPI) testing whether MSCI-style ESG ratings
> predict stock returns; found no significant return spread (sector-neutral Q5−Q1 {d.ne['spread_ret_ann_pct']:+.1f}%/yr,
> t = {d.ne['spread_t']:+.1f}) but a significant risk gradient (vol {r[0]['vol_ann_pct']:.1f}% → {r[4]['vol_ann_pct']:.1f}%), and
> published the sensitivity test that breaks the result.**

Shorter, for a one-line CV:

> **Python/FastAPI ESG-alpha study: quintile sorts + sector neutralisation + clustered regressions on
> {d.yn}; showed the 2022 ESG "underperformance" was a sector effect ({a['total_mix_effect_ann_pct']:+.1f} of {a['raw_spread_ann_pct']:+.1f} pts).**

For a consulting/generalist role, lead with the decision rather than the code:

> **Turned a contested ESG-vs-returns debate into a screening rule: buy rating improvements, not rating
> leaders; sell downside protection, not alpha. Backed by a reproducible pipeline anyone can re-run on
> their own data.**

---

## The 90-second answer (say it out loud three times)

> {o['verdict']['answers'][0]['detail']}

> {o['verdict']['answers'][1]['detail']}

> {o['verdict']['answers'][2]['detail']}

> {o['verdict']['answers'][3]['detail']}

---

## Follow-ups you should be ready for

**"How did you handle sector bias?"**
Sector-neutralising: for each firm-month I subtract the mean of its own sector that month, so a stock is
compared with genuinely comparable stocks. It moves the spread from {d.na['spread_ret_ann_pct']:+.1f}%/yr to
{d.ne['spread_ret_ann_pct']:+.1f}%/yr, and in {a['year']} alone the sector-mix term explains {a['total_mix_effect_ann_pct']:+.1f}
of the {a['raw_spread_ann_pct']:+.1f} points. That decomposition is an exact monthly identity — mix plus selection has
to equal the headline number — which is why it is hard to argue with.

**"Why cluster the standard errors?"**
Each firm appears ~{int(o['regressions']['specs'][0]['result']['n']/d.u['n_firms'])} times. Errors that assume independence would be far too
small and everything would look significant. Clustering by firm is the minimum correct thing to do; it is
also why my return result is *insignificant* and my risk result (t = {d.riskcoef['t']:+.1f}) is not.

**"Why equal weight and not cap weight?"**
Cap weighting imports a size tilt, so you would be measuring large-cap behaviour and calling it ESG. Equal
weight keeps the sort honest; cap-weighted is a robustness check I would run next.

**"What's the sample, and is it enough?"**
{d.yn} over {d.span}. It is enough to detect the risk gradient and not enough to rule out a modest return
premium — which is exactly how I worded the conclusion: "not detectable", never "zero".

**"Isn't your data fake?"**
The demo panel is generated, yes — from three named assumptions in one config file, and it is labelled as
synthetic in the header, the watermark, the deck and every figure caption. I did that deliberately: the
sandbox this was built in blocks Yahoo and Hugging Face, so instead of quietly substituting scraped numbers
I built the data layer so that a real ESG-Book/MSCI panel plus real prices goes in through `POST /api/upload`
or `data/panel.csv` and every number, sentence and slide regenerates. The analysis is the deliverable.

**"What would break your conclusion?"**
Three things: (i) real data with a survivorship-bias-free universe; (ii) a second ESG rater, since
cross-provider disagreement is large and a result that only exists on one scale is a methodology artefact;
(iii) transaction costs on the momentum leg — the momentum coefficient is the only significant return
effect and momentum is fragile and turnover-heavy.

**"So is ESG investing good or bad?"**
Neither question is answerable on this data, and that's the point of the project. What is answerable: as a
*return* promise it is not supported here; as a *risk* characteristic it clearly is. Those imply different
products, different fees and different clients, and conflating them is the actual industry problem.

---

## Numbers to memorise

| What | Value | Why it matters |
|---|---|---|
| Naive Q5−Q1 spread | {d.na['spread_ret_ann_pct']:+.1f}%/yr (t={d.na['spread_t']:+.1f}) | the headline everyone quotes |
| Sector-neutral spread | {d.ne['spread_ret_ann_pct']:+.1f}%/yr (t={d.ne['spread_t']:+.1f}) | the honest number |
| ESG momentum | {d.mom['bp_per_month']:+.1f} bp/mo per SD (t={d.mom['t']:+.2f}) | the only significant return result |
| Vol, Q1 → Q5 | {r[0]['vol_ann_pct']:.1f}% → {r[4]['vol_ann_pct']:.1f}% | where the signal is |
| Downside capture | {r[0]['downside_capture_pct']:.0f}% → {r[4]['downside_capture_pct']:.0f}% | how I would sell it |
| Worst drawdown | {r[0]['max_drawdown_pct']:.1f}% → {r[4]['max_drawdown_pct']:.1f}% | the client-facing number |
| {a['year']} mix effect | {a['total_mix_effect_ann_pct']:+.1f} of {a['raw_spread_ann_pct']:+.1f} pts | the debunking exhibit |

---

## What to open first, if they ask to see it

1. `environ/docs/deck.html` — 12 slides, arrow keys, prints to PDF.
2. The live dashboard — the **Sector trick** tab (that year selector is the best 30 seconds of the demo).
3. `environ/config.py` — the assumptions, on one page, in plain English.
4. Method & limits tab — shows you know what the analysis cannot do.
"""


# --------------------------------------------------------------------------- main
def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--panel", default=os.path.join(HERE, "data", "panel.csv"))
    ap.add_argument("--firms", default=os.path.join(HERE, "data", "firms.csv"))
    ap.add_argument("--no-figures", action="store_true", help="skip the matplotlib PNGs")
    args = ap.parse_args()

    os.makedirs(DOCS, exist_ok=True)
    if not args.no_figures:
        import subprocess

        subprocess.run([sys.executable, "-m", "environ.scripts.make_figures",
                        "--panel", args.panel, "--firms", args.firms, "--outdir", FIGS_DIR],
                       check=False, capture_output=True)
    d = Doc(load(args.panel, args.firms))

    md = memo(d)
    open(os.path.join(DOCS, "memo.md"), "w").write(md)
    html = md_to_html(md, "Does a high ESG score pay? — memo")
    open(os.path.join(DOCS, "memo.html"), "w").write(html)
    open(os.path.join(DOCS, "deck.html"), "w").write(deck(d))
    open(os.path.join(DOCS, "interview-pack.md"), "w").write(interview_pack(d))
    open(os.path.join(DOCS, "transcript.md"), "w").write(transcript(d))

    print("docs:")
    for f in sorted(os.listdir(DOCS)):
        p = os.path.join(DOCS, f)
        if os.path.isfile(p):
            print(f"  {f:22} {os.path.getsize(p):>8,} bytes")
    print(f"figures: {len(os.listdir(os.path.join(DOCS,'figures')))} pngs" if os.path.isdir(os.path.join(DOCS,'figures')) else "")


def transcript(d: Doc) -> str:
    """Spoken version of the deck, for practising."""
    o = d.o
    r = d.risk["rows"]
    a = d.a
    out = ["# Deck transcript\n\nRead this aloud once before presenting; the phrasing is deliberately plain.\n"]
    slides = [
        ("Title", f"Does a high ESG score pay? I spent a term hearing two different answers to that question, so "
                  f"I built the analysis that separates them. On {d.yn} of data: no return spread you can detect, "
                  f"a risk gradient you can, and the famous ESG underperformance turns out to be a sector bet."),
        ("Why", "The confusion is between two claims. Alpha says better-run firms are underpriced and will "
                "outperform. Risk says better-run firms fall less when things go wrong. If it's alpha you buy "
                "the leaders. If it's risk you're selling a different product at a different price."),
        ("Method", "Every month I rank firms into five equal buckets on their published ESG score and hold them "
                   "for a month. Then I do it again after subtracting what each firm's own sector did that month. "
                   "And I cluster standard errors by firm, because each firm appears about a hundred times."),
        ("Result 1", f"Taken at face value, top minus bottom is {d.na['spread_ret_ann_pct']:+.1f}% a year. "
                     f"Sector-neutral, {d.ne['spread_ret_ann_pct']:+.1f}% a year, t of {d.ne['spread_t']:+.1f}. "
                     "Two bars, same portfolios, one is a headline and one is an answer."),
        ("Result 2", f"Where the signal lives is risk. Volatility falls from {r[0]['vol_ann_pct']:.1f} to "
                     f"{r[4]['vol_ann_pct']:.1f} percent, downside capture from {r[0]['downside_capture_pct']:.0f} to "
                     f"{r[4]['downside_capture_pct']:.0f}, and the worst drawdown improves "
                     f"{r[0]['max_drawdown_pct']-r[4]['max_drawdown_pct']:.1f} points. It's "
                     f"{o['verdict']['risk_shape']['vol']} steps in the right direction, not a perfect line — I say that "
                     "because the middle buckets are where a chart like this gets checked."),
        ("Result 3", f"This chart is the whole debate. Look at {a['year']}: on that year the naive bar is "
                     f"{d.o['by_year']['naive'][d.o['by_year']['years'].index(a['year'])]:+.1f}% and the sector-neutral bar is "
                     f"{d.o['by_year']['sector_neutral'][d.o['by_year']['years'].index(a['year'])]:+.1f}%. Same stocks, same months."),
        ("Result 4", f"So I decomposed it. In {a['year']}, {a['total_mix_effect_ann_pct']:+.1f} points came from which sectors "
                     f"each book held, {a['total_selection_ann_pct']:+.1f} from stock-picking inside sectors. That sums to the "
                     "headline by construction. Energy was 81 percent up that year and it is, sensibly, in the bottom ESG "
                     "quintile — that is not an ESG failure, that is an energy call."),
        ("Result 5", f"The one significant return result is momentum, not the level: {d.mom['bp_per_month']:+.1f} basis points a "
                     f"month per standard deviation of rating improvement, t of {d.mom['t']:+.2f}. Buy the improvers, not the "
                     "leaders. With the caveat that momentum decays and this is before turnover."),
        ("Robustness", f"Four specifications, and the level coefficient wanders every time I add a control. That is not a "
                       "weakness of my analysis, it's the central fact of the literature — and the honest thing is to show "
                       "the intervals rather than the point estimate."),
        ("Honesty test", "I built a switch that sets the assumed ESG effects to zero and regenerates the panel. The verdict "
                         "text rewrites itself to a null. Any study that can't fail a test like that isn't a study."),
        ("Limits", "Synthetic demo data, fixed universe, one rater, no costs, correlation not causation. The fixed universe "
                   "actually flatters the number I'm criticising, so my conclusion is conservative in that one direction."),
        ("Recommendation", "Sell ESG as downside control, tilt on rating improvement, and never show an ESG return figure "
                           "without the sector-neutral one next to it. For a CFO: the ESG case is cost of capital, not growth."),
    ]
    for i, (t, b) in enumerate(slides, 1):
        out.append(f"\n### Slide {i} — {t}\n\n> {b}\n")
    return "".join(out)


# --------------------------------------------------------------------- tiny md->html
def md_to_html(md: str, title: str) -> str:
    import html as _html
    import re

    def inline(x: str) -> str:
        x = _html.escape(x, quote=False)
        x = re.sub(r"`([^`]+)`", r"<code>\1</code>", x)
        x = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", x)
        x = re.sub(r"(?<!\*)\*([^*\n]+)\*(?!\*)", r"<em>\1</em>", x)
        return x

    out, in_ul, in_ol = [], False, False
    for raw in md.splitlines():
        ln = raw.rstrip()
        if ln.startswith("## "):
            close = ("</ul>" if in_ul else "") + ("</ol>" if in_ol else "")
            out.append(close + "<h2>" + inline(ln[3:]) + "</h2>")
            in_ul = in_ol = False
        elif ln.startswith("### "):
            out.append("<h3>" + inline(ln[4:]) + "</h3>")
        elif ln.startswith("# "):
            out.append("<h1>" + inline(ln[2:]) + "</h1>")
        elif re.match(r"^\d+\.\s", ln):
            if not in_ol:
                out.append("<ol>")
                in_ol = True
            out.append("<li>" + inline(re.sub(r"^\d+\.\s+", "", ln)) + "</li>")
        elif ln.startswith("* "):
            if not in_ul:
                out.append("<ul>")
                in_ul = True
            out.append("<li>" + inline(ln[2:]) + "</li>")
        elif ln.strip() == "---":
            out.append("<hr/>")
        elif ln.strip() == "":
            if in_ul:
                out.append("</ul>")
                in_ul = False
            if in_ol:
                out.append("</ol>")
                in_ol = False
        elif ln.startswith("**") and ln.endswith("**") and len(ln) < 90:
            out.append("<h4>" + inline(ln.strip("*")) + "</h4>")
        else:
            if in_ul:
                out.append("</ul>")
                in_ul = False
            if in_ol:
                out.append("</ol>")
                in_ol = False
            out.append("<p>" + inline(ln) + "</p>")
    out.append("</ul>" if in_ul else "")
    out.append("</ol>" if in_ol else "")
    body = "\n".join(out)
    css = """
:root{--ink:#16181d;--muted:#6b7280;--line:#e4e7ec;--green:#1f5c46}
body{font:16.5px/1.7 Inter,-apple-system,"Segoe UI",Georgia,serif;color:var(--ink);margin:0;background:#f7f7f5}
main{max-width:780px;margin:0 auto;background:#fff;padding:3.4rem 3.6rem 2.6rem;box-shadow:0 0 0 1px var(--line)}
h1{font-size:31px;letter-spacing:-.025em;line-height:1.15;margin:0 0 .3rem}
h2{font-size:20px;margin:2.4rem 0 .5rem;letter-spacing:-.015em;border-bottom:1px solid var(--line);padding-bottom:.35rem}
h3{font-size:15px;color:var(--muted);font-weight:500;margin:.2rem 0 1.4rem}
h4{margin:1.4rem 0 .3rem;font-size:14px;letter-spacing:.05em;text-transform:uppercase;color:var(--green)}
p{margin:.55rem 0} code{background:#f2f2ef;padding:.1em .35em;border-radius:4px;font-size:.87em}
hr{border:0;border-top:1px solid var(--line);margin:1.8rem 0} ul,ol{padding-left:1.25rem}
li{margin:.45rem 0} strong{font-weight:660}
.bar{max-width:780px;margin:2rem auto .6rem;display:flex;justify-content:space-between;font-size:12.5px;color:var(--muted)}
.bar a{color:var(--green);text-decoration:none;font-weight:600}
@media print{body{background:#fff}main{box-shadow:none;padding:0}h2{break-after:avoid}}
"""
    return f"""<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/><title>{_html.escape(title)}</title>
<style>{css}</style></head><body>
<div class="bar"><span>MBA case package · generated from the analysis, not typed</span>
<span><a href="/">← dashboard</a> &nbsp; <a href="/deck">slides</a> &nbsp; <a href="#" onclick="print();return false">print / PDF</a></span></div>
<main>{body}</main></body></html>"""


if __name__ == "__main__":
    main()
